### ISSUE TITLE
add support for disk or partition parameter

### ISSUE THREAD

**Issue by lfarkas** [Tomas-M/iotop#12]
hi,
it's a very useful top, but lack a very important feature to be able to filter for a given partition or disk.
eg. i'd like to know hoe much data written a service. BUT suppose it write logs, db, user data etc. and I also would like to know how much data written into my system disk or root partition.
so a command line argument eg. / or /dev/sda2 would be very useful!
is it possible to add such a feature?

**Comment by bbonev** [comment]
Unfortunately that is not possible - the linux kernel keeps only aggregated info per process and IO operations on different devices/filesystems can not be distinguished. On the other hand there is IO data per block device, but for that there is no data about the process.
