### ISSUE TITLE
does it need certain font or coding to display?

### ISSUE THREAD

**Issue by EinProfispieler** [Tomas-M/iotop#15]
tried compile it under WSL2 ubuntu, display very odds.

![微信截图_20210629024811](https://user-images.githubusercontent.com/86020571/123688359-7aa74f80-d884-11eb-945c-691083cb12df.png)

**Comment by bbonev** [comment]
It does not require special font - everything used is standard Unicode characters. Unfortunately some of those are from a more recent Unicode standard and are not yet supported in all terminal/font/OS combinations. The bad news is that there is no way to detect the non-working combinations from the program.

For such cases there is the ASCII mode, check out the `U` shortcut.

**Comment by EinProfispieler** [comment]
Thank You, will do , now working with a more detailed READ.ME for iotop
