### ISSUE TITLE
IO column doesn't show values

### ISSUE THREAD

**Issue by ManuLinares** [Tomas-M/iotop#23]
IO column is always zero, so 

`-o, --only            only show processes or threads actually doing I/O
`

doesn't work.

**Comment by bbonev** [comment]
Can you share version of iotop and also version of Linux kernel?

It is a known problem with 5.14.x kernels and was fixed in iotop 1.20

**Comment by ManuLinares** [comment]
My mistake, it was indeed fixed in 1.20.
