### ISSUE TITLE
Don't show task_delayacct warning if SWAPIN and IO columns disabled

### ISSUE THREAD

**Issue by GreenReaper** [Tomas-M/iotop#26]
As noted in #21, SWAPIN and IO don't work if `task_delayacct` is not enabled.

While knowing this is important, it may not be crucial for the current use of iotop; and the message is distracting and continues to be displayed even if SWAPIN and IO are disabled, potentially overlapping useful information depending on screen width/height.

The user may also not wish to enable `task_delayacct` because it results in a performance overhead, or as it will be misleading, since delay for most services will only be available after they are restarted, which may be impractical for ad-hoc troubleshooting.

It would therefore be nice if it the message was only shown if either of the columns it relates to were enabled. Potentially, a brief notice could be shown on startup, and thereafter the columns would be disabled by default.

As a secondary matter, it might be worth allowing iotop to run without `CONFIG_TASK_DELAY_ACCT` enabled, not showing SWAPIN and IO. While I/O delay % can be useful information, just knowing reads/writes per process may be sufficient for the intended use.

**Comment by bbonev** [comment]
While solving #21 I decided to require `task_delayacct`.

What you say is that it would be better to make that optional, hide the missing functionality in case it is disabled and provide an option to enable it...

I agree, that would be better - more choice and freedom for the user :)
Are you sending a patch or are you going to wait for me to do it?

**Comment by GreenReaper** [comment]
Well, effectively it *is* now optional in the sense that iotop still runs with the feature compiled in, but off - so it makes sense to smooth out that experience.

I don't plan to submit a patch for this, you're welcome to address it - if it helps, I'd guess that the key part from my perspective ("don't show the warning if the columns are off") could be done simply by adding `&& (!config.f.hideswapin || !config.f.hideio)` to [this if statement](https://github.com/Tomas-M/iotop/blob/f22894c8f1761f5a80941019b5aad8f9b396c103/src/view_curses.c#L1369), unless I'm missing some other element that relies on them.

Those same config vars could be set to 1 `if (!initial_delayacct)` [after it is set in view_curses_init](https://github.com/Tomas-M/iotop/blob/f22894c8f1761f5a80941019b5aad8f9b396c103/src/view_curses.c#L1292) (maybe with a fprintf to write a warning about the lack of data, and sleep(2) to show it; or an input command if you want the warning to be acknowledged?)

[The Ctrl-T handler](https://github.com/Tomas-M/iotop/blob/f22894c8f1761f5a80941019b5aad8f9b396c103/src/view_curses.c#L1273) might also hide/show the columns appropriately, since the user probably wants to see then if it is being turned on, and they won't be as useful if the feature is turned off.

This leaves the existing warning in place, but it would only be shown if the user manually showed the relevant columns again, without the setting that makes them work being enabled; or if task_delayacct was disabled in another way while iotop was running - both cases in which a warning might be useful.

**Comment by bbonev** [comment]
To be more precise the GRAPH column is a moving average of IO and if IO is not there it should also be hidden. IMO the GRAPH column is the best way to sort the data, especially when there are processes that do big IO then pause and repeat. Also the `--only` option (`o` shortcut) prefers the average value from GRAPH but in case it is hidden uses READ+WRITE - this will also become not so smooth.

It is easy to add similar moving averages for READ and WRITE (or maybe even their sum) but the challenge is how to reorganize the display to accommodate all that data. Maybe the best way is to keep the display as is, and just add a toggle for the GRAPH column's data source from R/W/R+W/IO (and mask IO if not avail)...

I'd rather make the reverse logic of what you describe above (use the status of `task_delayacct` as the leading value) - my reasoning for that being that there is already a shortcut to toggle the sysctl and the column toggles should be secondary. In case `task_delayacct` is off, a big warning will show once at startup (with some key to close) and all those functions will be masked (internally toggling them will work but with no visible effect when they are masked). In case in the meantime `task_delayacct` becomes on, they will show up. Also a small red indicator that the sysctl is off in the place of `[freezed]` seems as a good idea.

Does that sound sane?

**Comment by GreenReaper** [comment]
That all sounds reasonable to me. I must admit, I'm more familiar with the python version which (I think?) lacks this graph - I saw the ?unknown? errors it showed when I upgraded Debian to the experimental kernel, and tried out iotop-c to see if it had been fixed here - so as the graph did not work properly on my setup, I was wondering what it was meant to do to start with. 😅

Sum (read+write) sounds like a reasonable alternative for the graph, but perhaps determining scale would be an issue? Or it could show a dot above/below if there are *any* writes/reads in that period? Hopefully it wouldn't confuse existing users. In any case hiding it for now is the simplest approach, and means more of the often-useful process command line is visible.

The thing I was thinking about when making column show/hide separate from the sysctl setting is that, as I read it, the sysctl controls whether data is collected from new processes, but if it is turned off existing ones have the structure, which may still be read. But it is not clear to me that it is updated when off. If the structure is there, but stale and therefore misleading, perhaps that is an even better reason to hide it.

As for the selected sort, would dynamically hiding the fields change that? Perhaps the sort would be moved to a column that was still valid, and it would avoid iterating through the hidden columns?

**Comment by bbonev** [comment]
It is not a problem to scale some data to 4 dots :) Without the moving average for filtering/sorting the display becomes too jumpy (IMO).

The heading may become GRAPH[R] / GRAPH[W] / GRAPH[RW] / GRAPH[IO], would that be clear?

About data collection - not exactly - the structures are always there but the kernel does not fill any data when the sysctl is off. And continues filling after turned on. That may become really confusing (0 current value and stale data in history).

Sort on valid columns that are hidden is intentionally there; masked ones should obviously be skipped. E.g. I like to sort down on TID and hide the TID column. But it is not nice that this is not indicated in some way...

**Comment by GreenReaper** [comment]
My concern with scaling was more what it is to be scaled to. I think I/0 was a simple 0-100% scale, but what is the maximum for reads or writes? And is it scaled relative just to its own history (I guess this is closest to what it was previously), or that of other processes/threads that it might be compare to visually?

I think those headings are clear, though maybe R+W rather than RW if there is room (assuming that is what it is).

**Comment by bbonev** [comment]
Check this: https://github.com/bbonev/iotop
