### ISSUE TITLE
FR: Amount of IO per time

### ISSUE THREAD

**Issue by pkese** [Tomas-M/iotop#36]
Besides 'accumulated', it would be nice to have a view that would present the amount of IO per unit of time (depending on how long iotop or process is running).

I tend to run iotop in `-Pa` mode in a background terminal, but after a while I forget how long is it since I started iotop, which makes it difficult to calculate how much IO a certain process had done per day.

**Comment by bbonev** [comment]
Thanks for the suggestion. Most of the data required to implement this is already there and it wouldn't be too hard to implement. Please note that processes' lifetime do not necessarily match iotop's lifetime and iotop can only calculate the rate for the intersection of the lifetimes...

**Comment by pkese** [comment]
Sure. Anyway it works.

I really love and appreciate this tool.  
`iotop` helped me to figure out that Firefox and Clickhouse together were writing about 1 TB of data each day to my SSD thus shortening lifespan of the disk. It didn't take much to fix the problem, but if I didn't have iotop, I'd just be scratching my head and asking myself, what the hell is eating away my SSD so rapidly.  
So thank you. ❤️
