### ISSUE TITLE
IO metrics are constantly zero on VMs

### ISSUE THREAD

**Issue by spookyrecharge** [Tomas-M/iotop#38]
I can see that iotop is working good on my hosts (AWS EC2), which have been configured half a year ago

But today I've tried to set up a new host (same on AWS EC2) with the same linux distro (Ubuntu 20.04) and now for some reason:
1. It asks me to launch iotop using sudo (due to vulnerability). It is ok for me to run it as sudo, no problem.
2. There was a warning `CONFIG_TASK_DELAY_ACCT not enabled in kernel, cannot determine SWAPIN and IO %`
no problem, executed `echo 1 > /proc/sys/kernel/task_delayacct` and warning disappeared. But IOPS are still not swing

I'm confused since versions of iotop are the same 0.6 (installed via apt both) and hosts are the same (distro, instance type etc)

Even when building iotop version 1.22 from source showing me 0% IOPS

![изображение](https://user-images.githubusercontent.com/5503131/179019076-230e3547-8a60-4a25-8ebf-235a99bd04b6.png)

I've tried btop++ and it is showing IOPS load, same as iostat

What I'm doing wrong?

**Comment by bbonev** [comment]
Let me clarify that iotop-py (0.6) and iotop-c (1.22) are different projects. This is iotop-c.

The difference that you observe is a change in Linux kernel. There is a boot option to enable that. Else all processes that are started before enabling the sysctl will not have the io and swapin counters enabled. It is not a problem in the program but a change in the kernel to save some cycles...
