### ISSUE TITLE
build error on centos7

### ISSUE THREAD

**Issue by devZer0** [Tomas-M/iotop#39]
i'm getting this error when trying to build on centos7

# make
DE bld/delayacct.o
cc: error: unrecognized command line option '-Wdate-time'
make: *** [bld/delayacct.o] Error 1

after removing -Wdate-time for testing, i'm getting

CC bld/view_curses.o
In file included from src/view_curses.c:26:0:
src/view_curses.c: In function 'view_curses':
src/view_curses.c:964:30: error: 'A_ITALIC' undeclared (first use in this function)
      attron(config.f.nocolor?A_ITALIC:COLOR_PAIR(RED_PAIR));
                              ^
src/view_curses.c:964:30: note: each undeclared identifier is reported only once for each function it appears in
make: *** [bld/view_curses.o] Error 1

**Comment by bbonev** [comment]
Yes, this is known, but will be included in next release.

Apply this patch and it will work:

https://src.fedoraproject.org/rpms/iotop-c/blob/epel7/f/iotop-c_oldlibs.patch

Or alternatively you can wait for the official epel7 update to pass testing:

https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2022-7ceb319040

**Comment by devZer0** [comment]
thanks!
