### ISSUE TITLE
FR: add iops count

### ISSUE THREAD

**Issue by devZer0** [Tomas-M/iotop#40]
wouldn't it be useful to have iotop monitor iops instead of read/write throughput, too ?
(to be able to determine which process is an iops hog , which totally matters, especially with ordinary hdd)

from linux process info, this should be available (syscr/syscw)

# cat /proc/2577/io
rchar: 231362397403320
wchar: 60299521079984
syscr: 8486645208
syscw: 2586473645
read_bytes: 191716084186159
write_bytes: 30517886778390
cancelled_write_bytes: 726028288

    rchar: number of bytes the process read, using any read-like system call (from files, pipes, tty...).
    wchar: number of bytes the process wrote using any write-like system call.
    syscr: number of read-like system call invocations that the process performed.
    syscr: number of write-like system call invocations that the process performed.
    read_bytes: number of bytes the process directly read from disk.
    write_bytes: number of bytes the process originally dirtied in the page-cache (assuming they will go to disk later).
    cancelled_write_bytes: number of bytes the process "un-dirtied" - e.g. using an "ftruncate" call that truncated pages from the page-cache.  
http://www.haifux.org/lectures/254/alice_and_bob_in_io_land/node51.html

**Comment by bbonev** [comment]
Currently `iotop-c` uses the kernel netlink interface - AFAIR this info is not available there; anyways it is not a problem to also fetch from `/proc` and display this data.

My main concern is how to organize the display - shortcuts for column hide/show are 0-9 and all are used; adding new columns will also require new shortcuts for show/hide and it seems that the IOPS r/w columns are best placed next to the corresponding IO columns - changing the shortcuts is not a good idea, adding new ones in the middle also does not look too sane. Most probably the proper way is to extend the current IO columns and include the IOPS value inside them (possibly with a shortcut to disable the IOPS, by default it will be shown).

**Comment by devZer0** [comment]
i think iops in iotop would be killer feature. there is no such tool which aggregates that information on a per process basis, afaik.

**Comment by bbonev** [comment]
I do not doubt that :)

As a comment on the info in the first message - iotop already fetches this data from `struct taskstats` (see `linux/taskstats.h`). Doing an extra read on `/proc/<pid>/io` would double the load. I will use the `read_syscalls`/`write_syscalls` fields from `struct taskstats`...

**Comment by bbonev** [comment]
To be precise `read_syscalls`/`write_syscalls` do not represent IOPS. I came to know by implementing that first and saw that the numbers didn't look right. E.g. a read syscall may fetch data from caches and that will not lead to an IO operation; a couple of write syscalls may be combined, etc, etc...

I will most probably commit that try in a branch and leave it as history because I see no real use of the number of syscalls when the important info is the number of IOPS.

**Comment by bbonev** [comment]
I am closing this issue because after some research I did not find how to get IOPS values per process
