### ISSUE TITLE
FR: Add option to toggle graph direction

### ISSUE THREAD

**Issue by Atemu** [Tomas-M/iotop#48]
I'm used to having graphs grow from right to left from many other tools including i.e. `btop`.

It feels more intuitive for me to have time go from left-to-right rather than right-to-left once the graph is written out.

It'd be great if this was configurable https://github.com/Tomas-M/iotop/issues/47

**Comment by bbonev** [comment]
I have no opinion which one is better. While adding an option is OK, I think that changing the default is a no go.

Yes, there are already way too many options, with your suggestions they will grow and #47 makes sense. BTW for my use cases I always change this or that, and I have already been thinking about a config file.
