### ISSUE TITLE
Build fails on Raspbian 64 lite (mno-stackrealign)

### ISSUE THREAD

**Issue by itiligent** [Tomas-M/iotop#54]
FYI when following repo instructions for install on debian:

make -j 

gives:

cc: error: unrecognized command-line option ‘-mno-stackrealign’; did you mean ‘-mno-strict-align’

**Comment by bbonev** [comment]
This have already been addressed, see e54591a9c95f6d6ed26db6045d4755f5114a73bb in https://github.com/bbonev/iotop

Most probably I forgot to push it to the main repo...
