### ISSUE TITLE
Add option for different characters for graphics

### ISSUE THREAD

**Issue by rbanffy** [Tomas-M/iotop#55]
When running `iotop` on the Linux console (and, I assume, any terminal without braille support), we are limited to the characters provided in the console font - that somewhat restricts what can be displayed - the graphs show as diamonds. The Linux console, and most VT-like terminals have, however, some semigraphic mosaic characters that can be used to convey the same kind of information.

One such set is the scan 9-7-5-3-1 lines, `⎽⎼─⎻⎺`, which can show one value per column (but 5 values rather than 4). Most physical terminals support these characters as well.

Linux console fonts can have 256 or 512 glyphs, as well as an extra Unicode table for more. With that, it'd be possible to support Braille and other symbols on the graphical console - this being a matter of font support for those. Unfortunately no font I tried bundled with Ubuntu, Debian, and Fedora did support them (I'll make feature requests for those on their respective bug trackers).

In the meantime, it'd be worth adding a theme command-line switch to select different graph character options.

With that done, we can start exploring different sets, such as the ITU T.100 set of "smoothed mosaic", which are in Unicode between U+1FB3C to U+1FB67. They offer 2 points at 4 heights per character cell, as a filled polygon, or a mix of fill rates (the 0-25-50% set from CP 437, which is commonly supported) and colors (as done in Sysdig's spectrogram display)

**Comment by bbonev** [comment]
The `--ascii` option uses plain ASCII characters and should work anywhere. Also there is some code that is intended to detect a linux console and disable unicode drawing - https://github.com/Tomas-M/iotop/blob/master/src/view_curses.c#L2169

On the other hand if you propose a patch with alternative unicode drawing chars, I will consider accepting that.

**Comment by rbanffy** [comment]
Console detection failed here because I am running it under tmux and TERM is "tmux-256color". I'll work on a patch with a couple extra character sets for the graphs.

**Comment by bbonev** [comment]
I am closing this as we can continue the discussion in #56
