### ISSUE TITLE
Commit cea4a5efb annuls the conditional cc flags of `HAVEWDTI` and `HAVESREA`. 

### ISSUE THREAD

**Issue by CostisC** [Tomas-M/iotop#58]
Hi @bbonev,
Commit cea4a5efb annuls the conditional cc flags of `HAVEWDTI` and `HAVESREA`. 

E.g. hard code the make variable to either 
`HAVEWDTI = yes`
or 
`HAVEWDTI = no`

and test by
`make -nB | grep -m1 'date-time'`

It makes no difference.

**Comment by bbonev** [comment]
Thanks for spotting, fixed :)
