### ISSUE TITLE
98% CPU use

### ISSUE THREAD

**Issue by realnc** [Tomas-M/iotop#60]
Is it normal that iotop consumes 98% CPU when running? It completely hogs one CPU core.

I'm using version 1.24.

![2023-10-05-14-03-00-251980868](https://github.com/Tomas-M/iotop/assets/1665903/519236ec-457a-4537-9473-c91e3ae25055)

**Comment by bbonev** [comment]
No, it is not normal.

Please provide more info on how to reproduce that.

**Comment by realnc** [comment]
> No, it is not normal.
> 
> Please provide more info on how to reproduce that.

I just run iotop (as user.) I get a warning about task_delayacct. When the warning is shown, CPU use is quite normal. When I press ESC to hide the warning, CPU use goes to 98%.

Actually, as I'm writing this, I found out it happens even without the warning. If I instead press any other key to hide the warning, CPU use is normal. If I press ESC in iotop, CPU use skyrockets.

**Comment by bbonev** [comment]
Thank you for reporting this problem.

The good news is that it is 100% reproducible.

The problem is unrelated to running `iotop` as user or root.
It is also unrelated to the warning window - with or without it, an `ESC` key makes `iotop` to busy loop.
The problem is also present in v 1.23
