### ISSUE TITLE
Brew Package

### ISSUE THREAD

**Issue by mayurankv** [Tomas-M/iotop#62]
Would it be possible to have a brew package for this? It looks great!

**Comment by bbonev** [comment]
`iotop` is Linux specific and without major changes will not work on MacOS.

Maybe the performance counters used by `iotop` are also present in MacOS and it would be possible to add support. I'd rather rely on someone else to contribute the code (I do not have access to a MacOS machine).

**Comment by mayurankv** [comment]
Ah, I'm probably not well-versed enough to do this but which files would be a good starting point to look at?

**Comment by bbonev** [comment]
The Linux specific bits are in:

src/xxd_info.c [most important]
src/vmstat.c
src/ioprio.c
src/delayacct.c
src/checks.c

Maybe there are more, the above list is by a quick glance and I tried to sort it by importance...

**Comment by mayurankv** [comment]
I'll try to find some time to see if I can make them work with macOS!
