### ISSUE TITLE
Why can't iotop provide data io for directories?

### ISSUE THREAD

**Issue by gitthnx** [Tomas-M/iotop#71]
[Question] Why is there no option for iotop for monitoring directory io? (thx)

**Comment by bbonev** [comment]
Because the kernel does not provide counters for that

**Comment by gitthnx** [comment]
> Because the kernel does not provide counters for that

Thanks for Your response.

Do You see purpose for monitoring directories and are there different methods than kernel counters for aquiring io data or statistics for disk data rates?  

Can You please give me a pointer, where in iotop sources the gathering of kernel counters and read/write counting of processes (views.c?) is done?

Thank You for Your time and work.

**Comment by bbonev** [comment]
See xxxid_info.c for per process counters.

In vmstat.c only per system counters are collected.

I think that counting directory accesses may be done via eBPF but that will affect performance and is not suitable for a generic tool as iotop.

I am not sure what exactly you want to see related to directories? Most of the slow stuff happens during file IO.

**Comment by gitthnx** [comment]
> See xxxid_info.c for per process counters.
> 
> In vmstat.c only per system counters are collected.

 
> I think that counting directory accesses may be done via eBPF but that will affect performance and is not suitable for a generic tool as iotop.

It would be just for a rough overview, if a directory (dynamically) sees ~100kB data io or is burdened with ~10GB (e.g. for a log files directory). I'll have a look at eBPF, but i think it is too detailed for a simple overview (monitoring tool).

> I am not sure what exactly you want to see related to directories? Most of the slow stuff happens during file IO. 

one possible use case could be benchmarking filesystems (more towards detailed eBPF method) or monitoring specified directories with OS distribution upgrades or with updates of system drivers or expansive programs or frameworks; 
we tried to explain that on stackoverflow with finding an use case for that question/answer format ( https://unix.stackexchange.com/questions/778729/why-is-it-impossible-getting-efficiency-information-for-data-rate-output-or-sum ), but honestly Your replies are way more efficient, what's another positive for github based development. (thx)
