### ISSUE TITLE
[ARMv7] No disk visible disk actions

### ISSUE THREAD

**Issue by vinibali** [Tomas-M/iotop#74]
Hello there!
I'm having problems on my ARMv7 (Marvell 380) powered NAS running Arch Linux ARM.
Is just kicked off the iotop -o and I just got so surprised that all the processes are there and none of the processes are showing any activity. I'm running the iotop with the setcap options as user, but the case is pretty much when running as root.
Is there a Kernel configuration, which might not turned on on this build?
Thanks for this great project

**Comment by vinibali** [comment]
Update:
the python based iotop is able to show the disk usage for the processes, although it says:
```
CONFIG_TASK_DELAY_ACCT not enabled in kernel, cannot determine SWAPIN and IO %
```

**Comment by bbonev** [comment]
As long as it runs, most probably there is nothing missing. In newer kernels the delayacct ioctl is off by default and processes started before that is enabled, will always get 0 in the IO and SWAPIN counters. There is a shortcut (Ctrl-T) to toggle this.

Note that -o checks different counters depending on delayacct ioctl. If that is off it will look in READ/WRITE, else in IO.

Also it is important how your NAS is configured - e.g. if you use samba, the io is from a process, but in certain iSCSI setups the io is in the kernel only. iotop only monitors processes and may not see the in kernel io, unless it is on a kernel thread.

**Comment by vinibali** [comment]
Thanks for the response, I double checked this and it's just working fine now.
I wish you to have a great time and a happy new year!
Best regards
