### ISSUE TITLE
Build and test for Linux/ARM64 

### ISSUE THREAD

**Issue by odidev** [Tomas-M/iotop#77]
For aarch64 platform, I have built "iotop" from source.  

   

## Steps   

Following [STEPS](https://github.com/Tomas-M/iotop?tab=readme-ov-file#how-to-build-from-source) were used for the building and installation:  

  

``` 

sudo apt update 

sudo apt install -y wget make build-essential libncurses5-dev libncursesw5-dev 

wget https://github.com/Tomas-M/iotop/archive/refs/tags/v1.18.tar.gz 

tar -xvf v1.18.tar.gz 

cd iotop-1.18/ 

make -j$(nproc) 

make install 

```  

  

## Outcome  

To validate that the build was successful we ran a version check. The version info returned matched expected value(s).  

  

All this information is also added to Software Ecosystem Dashboard for Arm (https://www.arm.com/developer-hub/ecosystem-dashboard/).

**Comment by bbonev** [comment]
I do not understand why you build version 1.18
